import Head from 'next/head'

export default function App() {
  return (
    <div>
      <Head>
        <title>Create TCS App</title>
        <meta name="description" content="Generated by create tcs app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome!</h1>
        <p>
          Get started by editing{' '}
          <code>pages/index.js</code>
        </p>
      </main>
    </div>
  )
}
